GET http://127.0.0.1:3000/account
content-type: application/json

# {
#     "author": "root vtori",
#     "ingredients" : "domati, krastavici",
#     "recipe": "test recipe 22",
#     "image": ""
# }

# {
#     "username": "root vtori",
#     "password": "1234"
# }

# {
#     "ingredients": "sustavki test 4",
#     "recipe": "test recipe 4"
# }